services:
  connector-database:
    restart: always
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - ./env/connector-database.env
    networks:
      - all-network
    volumes:
      - /tmp/cloud-connector-db/:/var/lib/postgresql/data/

  rabbit-mq:
    image: "rabbitmq:latest"
    env_file:
      - ./env/rabbitmq.env
    ports:
      - 5672:5672
    networks:
      - all-network
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - '-q'
        - ping
      retries: 3
      timeout: 5s
      interval: 10s
    volumes:
      - /tmp/rabbitmq/:/var/lib/rabbitmq

  cloud-connector:
    restart: always
    depends_on:
      - connector-database
      - rabbit-mq
    build: https://github.com/zarinit-routers/cloud-connector.git
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - all-network
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbit-mq:5672/"
      CONNECTOR_GRPC_ADDR: "connector:8081"
      DATABASE_CONNECTION_STRING: "host='connector-database' user='connector' password='CoolPassword123' port='5432' dbname='connector-db' sslmode=disable"
      DATABASE_AUTO_MIGRATE: true
    develop:
      watch:
        - action: rebuild
          path: .

  cloud-server:
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - cloud-connector
      - rabbit-mq
    build: https://github.com/zarinit-routers/cloud-server.git
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbit-mq:5672/"
      CONNECTOR_GRPC_ADDR: "connector:8081"
    networks:
      - all-network

networks:
  all-network:
    driver: bridge
