services:
  connector-database:
    restart: always
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - ../cloud-connector/env/postgres.env
    networks:
      - all-network
    volumes:
      - /tmp/cloud-connector-db/:/var/lib/postgresql/data/

  rabbit-mq:
    image: "rabbitmq:latest"
    env_file:
      - ../cloud-connector/env/rabbitmq.env
    ports:
      - 5672:5672
    networks:
      - all-network
    healthcheck:
      test:
        - CMD
        - rabbitmq-diagnostics
        - '-q'
        - ping
      retries: 3
      timeout: 5s
      interval: 10s
    volumes:
      - /tmp/rabbitmq/:/var/lib/rabbitmq

  connector:
    restart: always
    depends_on:
      - connector-database
      - rabbit-mq
    build: https://github.com/zarinit-routers/cloud-connector.git
    ports:
      - 8080:8080
    networks:
      - all-network
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbit-mq:5672/"
    develop:
      watch:
        - action: rebuild
          path: .

  server:
    restart: always
    depends_on:
      - connector
      - rabbit-mq
    build: https://github.com/zarinit-routers/cloud-server.git
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbit-mq:5672/"
    networks:
      - all-network

networks:
  all-network:
    driver: bridge
